theme: jekyll-theme-minimal
title: Matthew Silcocks
description: This portfolio shows some examples of my previous work, including a working example of an object-oriented C++ program.<br /><br />My contact details are available on my CV.

